a=float(input()) #getting a float input
ans=0.25*((3**0.5)*(a**2))#1/4=0.25,root of 3=3**0.5 and a**2.....this is the formula to find equatorial triangle area...
print(round(ans,2))#finaly round a float to two values and than print
